substitutions:
  project_name: "ajs.Light - Matrix Lamp"
  project_version: "1.5.13"
  comment: "ESPHome Matrix Lamp"

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 5s
      - logger.log:
          format: "${friendly_name} started, LED: ${type_leds}:${num_leds}:${pin_leds}, Effects: %d Reboot: ${reboot_timeout}"
          args: ['id(neopixel_led)->get_effects().size()']
          level: INFO
          tag: start

external_components:
  - source:
      type: git
      url: https://github.com/andrewjswan/esphome-components
      ref: main
    components: [fastled_helper]
    refresh: 60s
  - source:
      type: git
      url: https://github.com/iakunin/matrix-lamp
      ref: main
    components: [matrix_lamp]
    refresh: 60s

fastled_helper:
  palettes: false

matrix_lamp:
  id: matrix
  width: 16
  height: 16
  random: true
  matrix_type: 0

number:
  # Matrix Orientation
  - platform: template
    name: Matrix Orientation
    icon: mdi:autorenew
    min_value: 1
    max_value: 8
    step: 1
    optimistic: true
    id: matrix_orientation
    initial_value: 4
    mode: slider
    entity_category: config
    disabled_by_default: true
    restore_value: true
    on_value:
      then:
        - lambda: |-
            id(matrix).set_matrix_orientation(x);
